//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется Res.rc
//
#define MainPopupMenu                   105
#define ButtonPopupMenu                 126
#define IDD_DIALOG1                     173
#define IDI_ICON1                       182
#define IDI_PASSICON                    185
#define IDI_ICON2                       188
#define IDB_BITMAP1                     189
#define IDB_BITDELA                     189
#define IDB_BITMAP2                     190
#define IDB_BITPRIM                     190
#define IDB_BITMAP3                     191
#define IDB_BITROV                      191
#define IDB_BITMAP4                     192
#define IDB_BITPRAZ                     192
#define IDB_BITMAP5                     193
#define IDB_BITIMEN                     193
#define IDI_ICON3                       194
#define IDI_ICON4                       198
#define IDB_BITEVENT                    201
#define IDB_BITPRAV                     205
#define IDI_ICON5                       206
#define IDB_BITMAP6                     208
#define IDI_ICON8                       212
#define IDC_MESSAGELABEL                1014
#define IDC_PARAMLABEL                  1015
#define ID_TODAY                        1017
#define IDC_COMBO1                      1018
#define IDC_EDIT1                       1019
#define IDC_EDITNAME                    1019
#define IDC_EDIT2                       1020
#define IDC_EDIT3                       1021
#define IDC_EDITPREFIX                  1021
#define IDC_EDIT4                       1022
#define IDC_EDIT5                       1023
#define IDC_EDIT6                       1024
#define IDC_EDIT7                       1025
#define IDC_EDIT8                       1026
#define IDC_EDIT9                       1027
#define IDC_EDIT10                      1028
#define IDC_EDIT11                      1029
#define IDC_LIST1                       1030
#define IDC_EDIT12                      1031
#define IDC_LIST3                       1032
#define IDC_BUTTON1                     1033
#define IDC_BUTTON2                     1034
#define IDC_BUTTON3                     1035
#define IDC_BUTSTOP                     1035
#define IDC_BUTUP2                      1035
#define IDC_BUTTON4                     1036
#define IDC_BUTDOWN2                    1036
#define IDC_NOTEEDIT1                   1037
#define IDC_INPEDIT1                    1038
#define IDC_PASSEDIT1                   1039
#define IDC_CHECK1                      1040
#define IDC_BOOTCHECK                   1040
#define IDC_COMBO2                      1041
#define IDC_COMBOTIME                   1041
#define IDC_CBCITY                      1041
#define IDC_GROUP1                      1042
#define IDC_LIST2                       1053
#define IDC_LISTUNIT                    1053
#define IDC_STATICNOMER                 1056
#define IDC_TAB1                        1057
#define IDC_ICONCHECK                   1058
#define IDC_AUTOCHECK                   1059
#define IDC_RADIO1                      1060
#define IDC_AUTOCHECK2                  1060
#define IDC_ALWAYSONTOP                 1060
#define IDC_RADIO2                      1061
#define IDC_PULSECHECK                  1062
#define IDC_DATASTATIC                  1063
#define IDC_COLSTATIC                   1064
#define IDC_CHECK2                      1065
#define IDC_BUTPLAY                     1066
#define IDC_LISTFOLDER                  1067
#define IDC_BUTOFF                      1067
#define IDC_BUTUP1                      1068
#define IDC_BUTDOWN1                    1069
#define IDC_SLIDER1                     1070
#define IDC_DNEVLIST                    1071
#define IDC_SLIDER2                     1071
#define IDC_BUTUP3                      1073
#define IDC_BUTDOWN3                    1074
#define IDC_CHECKDIARYAUTO              1075
#define IDC_BUTSYNC                     1076
#define IDC_STATICTIME                  1077
#define IDC_CHSHOWFULL                  1078
#define IDC_CBDELEVENT                  1079
#define IDC_CHFULLIMEN                  1080
#define IDC_CBDELDELA                   1081
#define IDC_CHSKYINFO                   1082
#define IDC_EDITGEOD                    1083
#define IDC_EDITGEOS                    1084
#define IDC_CHECKTIT                    1085
#define IDC_LABTEXT                     1086
#define IDC_SLIDER3                     1087
#define IDC_STATIC_T0                   1088
#define IDC_STATIC_T100                 1089
#define IDC_STATIC_TGR                  1090
#define ID_AUTOHIDE                     40001
#define ID_ADDTOPIC                     40002
#define IDD_DELETETOPIC                 40003
#define ID_EXIT                         40004
#define ID_OPTION                       40005
#define ID_UPDATEICON                   40006
#define ID_UNITHIDE                     40008
#define ID_UNITDELETE                   40009
#define ID_UNITPROP                     40010
#define ID_UNITCRLNK                    40011
#define ID_UNITRENAME                   40012
#define IDC_ABOUT                       40013
#define ID_ADDICON                      40015
#define ID_RENAMEFOLDER                 40016
#define ID_ADDSPLITTER                  40017
#define IDC_FOLDEROPTION                40018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         40019
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
